version: '3'
services:
  edge-runtime:
    image: supabase/edge-runtime:v1.67.4
    ports:
      - "8000:8000"
    volumes:
      - ./functions:/home/deno/functions:ro
    environment:
      - SUPABASE_URL=https://uozcfpvkexesggtkfdtg.supabase.co
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
